name: prayer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  connectivity_plus: ^6.1.1
  flutter:
    sdk: flutter
  flutter_qiblah: ^3.0.4
  flutter_svg: ^2.0.16
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  location: ^7.0.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_launcher_icons: "^0.14.2"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mosque.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/mosque.png"
flutter:
  uses-material-design: true
  assets :
    - assets/images/
